[package]
name = "day_6"
version = "0.1.0"
authors = ["dejef <dejef@pdx.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.19"